[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.9.0"

[[repos.hooks]]
id = "ruff"
args = ["--fix"]

[[repos.hooks]]
id = "ruff-format"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "trailing-whitespace"

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "check-yaml"

[[repos.hooks]]
id = "check-toml"

[[repos.hooks]]
id = "check-added-large-files"
args = ["--maxkb=500"]
